# Generated by Django 3.1.3 on 2023-12-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='가게명')),
                ('info', models.TextField(verbose_name='소개')),
                ('hp', models.CharField(max_length=15, verbose_name='전화번호')),
                ('operated_date', models.CharField(max_length=128, verbose_name='운영시간')),
                ('address', models.CharField(max_length=128, verbose_name='주소')),
            ],
            options={
                'verbose_name': '빵집 리스트',
                'verbose_name_plural': '빵집 리스트',
                'db_table': '빵집 리스트',
            },
        ),
    ]
